meta_title: "Hook - You know how, we know where"
meta_description: "The app that records your catches and finds the best fishing spots!"
meta_image: "cover.png"
meta_icon: "hook-icon.png"
twitter_account: "@Lewagonparis"  # Le Wagon twitter account... We don't have one
