meta_title: "Hook"
meta_description: "The app that records your catches and finds the best fishing spots!"
meta_image: "cover.png"
meta_icon: "favicon.png"
twitter_account: "@Lewagonparis"  # Le Wagon twitter account... We don't have one
